name: Lint package [on PR]

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: yarn
      - run: yarn lint
      - run: yarn build
